#!/bin/bash
continuous="true"

SOURCE_DOMAIN="MYDOMAIN_TLD___"
SOURCE_ADMIN_USERNAME="nicer_app___rene_ajm_veerman"
SOURCE_ADMIN_PW="anImpossiblyStrongPW"
SOURCE_IP="192.168.178.29"
SOURCE_PORT="5984"

TARGET_DOMAIN="MYDOMAIN_TLD___"
TARGET_ADMIN_USERNAME="admin"
TARGET_ADMIN_PW="someF4aancyPW!"
TARGET_IP="192.168.178.24"
TARGET_PORT="5984"

SOURCE_HOST="http://${SOURCE_ADMIN_USERNAME}:${SOURCE_ADMIN_PW}@${SOURCE_IP}:${SOURCE_PORT}/${SOURCE_DOMAIN}"
TARGET_HOST="http://${TARGET_ADMIN_USERNAME}:${TARGET_ADMIN_PW}@${TARGET_IP}:${TARGET_PORT}/${TARGET_DOMAIN}"
